---
  Profiles: 
    oneorgorderergenesis: 
      Orderer: 
        OrdererType: "solo"
        Addresses: 
          - "orderer8.example.com:7050"
        BatchTimeout: "2s"
        BatchSize: 
          MaxMessageCount: 10
          AbsoluteMaxBytes: 99000000
          PreferredMaxBytes: 512000
        Organizations: 
          - 
            Name: "Orderer8"
            ID: "Orderer8MSP"
            MSPDir: "crypto-config/ordererOrganizations/example.com/msp"
      Consortiums: 
        SampleConsortium: 
          Organizations: 
            - 
              Name: "Org0MSP"
              ID: "Org0MSP"
              MSPDir: "crypto-config/peerOrganizations/org0.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org0.example.com"
                  Port: "7051"
            - 
              Name: "Org1MSP"
              ID: "Org1MSP"
              MSPDir: "crypto-config/peerOrganizations/org1.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org1.example.com"
                  Port: "8051"
            - 
              Name: "Org2MSP"
              ID: "Org2MSP"
              MSPDir: "crypto-config/peerOrganizations/org2.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org2.example.com"
                  Port: "9051"
            - 
              Name: "Org3MSP"
              ID: "Org3MSP"
              MSPDir: "crypto-config/peerOrganizations/org3.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org3.example.com"
                  Port: "10051"
    channelone: 
      Consortium: "SampleConsortium"
      Application: 
        Organizations: 
          - 
            Name: "Org0MSP"
            ID: "Org0MSP"
            MSPDir: "crypto-config/peerOrganizations/org0.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org0.example.com"
                Port: "7051"
          - 
            Name: "Org1MSP"
            ID: "Org1MSP"
            MSPDir: "crypto-config/peerOrganizations/org1.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org1.example.com"
                Port: "8051"
          - 
            Name: "Org2MSP"
            ID: "Org2MSP"
            MSPDir: "crypto-config/peerOrganizations/org2.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org2.example.com"
                Port: "9051"
          - 
            Name: "Org3MSP"
            ID: "Org3MSP"
            MSPDir: "crypto-config/peerOrganizations/org3.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org3.example.com"
                Port: "10051"
