---
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
        # V1.1 for Global is a catchall flag for behavior which has been
        # determined to be desired for all orderers and peers running v1.0.x,
        # but the modification of which would cause incompatibilities.  Users
        # should leave this flag set to true.
        V1_1: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
        # V1.1 for Order is a catchall flag for behavior which has been
        # determined to be desired for all orderers running v1.0.x, but the
        # modification of which  would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_1: true

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
        # V1.2 for Application is a catchall flag for behavior which has been
        # determined to be desired for all peers running v1.0.x, but the
        # modification of which would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_2: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

Profiles: 
    oneorgorderergenesis: 
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        Capabilities:
          <<: *OrdererCapabilities
        OrdererType: "solo"
        Addresses: 
          - "orderer8.example.com:7050"
        BatchTimeout: "2s"
        BatchSize: 
          MaxMessageCount: 10
          AbsoluteMaxBytes: 99000000
          PreferredMaxBytes: 512000
        Organizations: 
          - 
            Name: "Orderer8"
            ID: "Orderer8MSP"
            MSPDir: "crypto-config/ordererOrganizations/example.com/msp"
      Consortiums: 
        SampleConsortium: 
          Organizations: 
            - 
              Name: "Org0MSP"
              ID: "Org0MSP"
              MSPDir: "crypto-config/peerOrganizations/org0.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org0.example.com"
                  Port: "7051"
            - 
              Name: "Org1MSP"
              ID: "Org1MSP"
              MSPDir: "crypto-config/peerOrganizations/org1.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org1.example.com"
                  Port: "8051"
            - 
              Name: "Org2MSP"
              ID: "Org2MSP"
              MSPDir: "crypto-config/peerOrganizations/org2.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org2.example.com"
                  Port: "9051"
            - 
              Name: "Org3MSP"
              ID: "Org3MSP"
              MSPDir: "crypto-config/peerOrganizations/org3.example.com/msp"
              AnchorPeers: 
                - 
                  Host: "peer0.org3.example.com"
                  Port: "10051"
    channelone: 
      Consortium: "SampleConsortium"
      Application:
          <<: *ApplicationDefaults
      Application: 
        Organizations: 
          - 
            Name: "Org0MSP"
            ID: "Org0MSP"
            MSPDir: "crypto-config/peerOrganizations/org0.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org0.example.com"
                Port: "7051"
          - 
            Name: "Org1MSP"
            ID: "Org1MSP"
            MSPDir: "crypto-config/peerOrganizations/org1.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org1.example.com"
                Port: "8051"
          - 
            Name: "Org2MSP"
            ID: "Org2MSP"
            MSPDir: "crypto-config/peerOrganizations/org2.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org2.example.com"
                Port: "9051"
          - 
            Name: "Org3MSP"
            ID: "Org3MSP"
            MSPDir: "crypto-config/peerOrganizations/org3.example.com/msp"
            AnchorPeers: 
              - 
                Host: "peer0.org3.example.com"
                Port: "10051"
        Capabilities:
          <<: *ApplicationCapabilities

